### ISSUE TITLE
Create a goodness of fit module in hyppo

### ISSUE THREAD

**Issue by sampan501** [neurodata/hyppo#103]
http://papers.nips.cc/paper/6630-a-linear-time-kernel-goodness-of-fit-test
https://dl.acm.org/doi/10.5555/3305381.3305561

are two examples

**Comment by sampan501** [comment]
Can also wrap out `KSample` class where the first sample is the data, and the second sample is a random generated data set derived from the distribution desired to be tested against. Compare against the above tests

**Comment by darsh-patel** [comment]
interested
