### ISSUE TITLE
Add fast HHG

### ISSUE THREAD

**Issue by sampan501** [neurodata/hyppo#106]
https://papers.nips.cc/paper/6220-multivariate-tests-of-association-based-on-univariate-tests

Maybe good to test against in the fast Dcorr paper

**Comment by sampan501** [comment]
If we don't include the fast HHG independence test, which is fine, there is also a fast 2-sample test that should definitely be included

**Comment by TacticalFallacy** [comment]
Gave this one a read! Think I'll like to try my hand at this.
