### ISSUE TITLE
ksample: check variance of transformed samples, not original samples

### ISSUE THREAD

**Issue by eigenvivek** [neurodata/hyppo#113]
K-sample testing should check for zero variance in the transformed samples, not the original samples.

#### Reproducable code example
The following code returns `ValueError: Test cannot be run, one of the inputs has 0 variance` when it shouldn't.
```python
import numpy as np
from hyppo.ksample import KSample

x = np.array([1, 1, 1, 1, 1])
y = np.array([2, 2, 2, 2, 2])

stat, pval = KSample("Dcorr").test(x, y)
```

Because K-Sample testing concatenates these samples into `u = {1, 1, 1, 1, 1, 2, 2, 2, 2, 2}` and `v = {0, 0, 0, 0, 0, 1, 1, 1, 1, 1}`, the actual samples being tested do not have zero variance.

However, the current implementation of the `_CheckInputs` class checks for zero variance on the original samples, not these transformed samples (see code [here](https://github.com/neurodata/hyppo/blob/e1f16735ce4c3572ab6fdc2f3f41d92376199e6b/hyppo/ksample/_utils.py#L73-L76)).

We could either
1. change the `__call__` function of `_CheckInputs` or
2. include a `check_variance` within `k_sample_transform`

#### Version information
hyppo version 0.1.3

**Comment by sampan501** [comment]
I think the best thing to do take out the `check_variance` in `_CheckInputs` and add an "if-raise" error check [here](https://github.com/neurodata/hyppo/blob/e1f16735ce4c3572ab6fdc2f3f41d92376199e6b/hyppo/ksample/_utils.py#L82) for `u`

**Comment by eigenvivek** [comment]
want me to do that today? more than happy to

**Comment by sampan501** [comment]
yes that would be great
