### ISSUE TITLE
hyppo is much slower than mgcpy for mgc test

### ISSUE THREAD

**Issue by fxyw** [neurodata/hyppo#123]
```
import seaborn as sns
dfac = sns.load_dataset("anscombe")
from mgcpy.independence_tests.mgc import MGC
def mgc(x,y):return MGC().test_statistic(np.array(x).reshape(-1, 1), np.array(y).reshape(-1, 1))[0]
from hyppo.independence import MGC as MGC1
def mgc1(x,y):return MGC1().test(np.array(x).reshape(-1, 1), np.array(y).reshape(-1, 1))[0]
```
```
%%time
dfac.groupby('dataset').apply(lambda x: mgc1(x['x'],x['y']))
```

Wall time: 10.6 s
dataset
I      0.580259
II     0.709312
III    0.995959
IV     0.387116
dtype: float64

```
%%time
dfac.groupby('dataset').apply(lambda x: mgc(x['x'],x['y']))
```

Wall time: 19 ms
dataset
I      0.580259
II     0.709312
III    1.000000
IV     0.387116
dtype: float64

```
import platform; print(platform.platform())
import sys; print("Python", sys.version)
import hyppo; print("hyppo", hyppo.__version__)
```

Windows-2012ServerR2-6.3.9600-SP0
Python 3.6.8 |Anaconda, Inc.| (default, Feb 21 2019, 18:30:04) [MSC v.1916 64 bit (AMD64)]
hyppo 0.1.3

**Comment by sampan501** [comment]
So it looks like you are comparing `mgcpy`'s test statistic wall times to `hyppo`'s test statistic and p-value computation. I think a more apt comparison is between the `p_value` method from `mgcpy` and the `test` method from `hyppo`.

Also, the `hyppo` `test` method is parallelized, which should yield even faster results.

**Comment by fxyw** [comment]
Thank you for remind me this. I will check the mgcpy p_value time. Is there a way for hyppo to only calculate test statistics ?

**Comment by sampan501** [comment]
There is, each test should have a `_statistic` method, though this is generally used internally and doesn't have as robust error checking. I would recommend using the `test` method and setting `reps=0`.

**Comment by fxyw** [comment]
The time is actually used in p_value calculation, hyppo 10.6s s vs mgcpy’s  12.3s. With reps=0, the hyppo used time 30ms is inline with mgcpy’s  19ms.

```
%%time
dfac.groupby('dataset').apply(lambda x: MGC().p_value(np.array(x['x']).reshape(-1, 1), np.array(x['y']).reshape(-1, 1))[0])
```

Wall time: 12.3 s
dataset
I      0.009
II     0.004
III    0.001
IV     0.089
dtype: float64

```
%%time
dfac.groupby('dataset').apply(lambda x: MGC1().test(np.array(x['x']).reshape(-1, 1), np.array(x['y']).reshape(-1, 1),reps=0)[0])
```


Wall time: 30 ms

dataset

I      0.580259

II     0.709312

III    0.995959

IV     0.387116

dtype: float64


Thanks for providing this option.
