### ISSUE TITLE
Discriminability `y` should allow arbitrary type or make docs more clear

### ISSUE THREAD

**Issue by bdpedigo** [neurodata/hyppo#140]
**Is your feature request related to a problem? Please describe.**
Currently, the `y` argument to `Discriminability.test(x, y)` will raise an error if a vector of strings is passed. The error is just that a string array cannot be cast to float.

The docs currently just say `nd.array` and don't clarify what type of values are accepted. (See [here](https://github.com/neurodata/hyppo/blob/2f4406eb175446d683d0d052bf7befa57b5c801f/hyppo/discrim/discrim_one_samp.py#L87))

**Describe the solution you'd like**
I don't see why the `y` argument needs to be cast to float ([here](https://github.com/neurodata/hyppo/blob/2f4406eb175446d683d0d052bf7befa57b5c801f/hyppo/discrim/_utils.py#L33)), but maybe I'm missing something? From a quick look at the code I don't think anything would break if you just didn't cast this array. Especially since most of the time, these will be ints, i'd imagine.

**Describe alternatives you've considered**
If you disagree or I'm wrong, the docs should at least be clarified as to what types are accepted, and a check for that data type in the array seems reasonable.

**Comment by ghost** [comment]
@sampan501 Hi, I can modify this if it is still open. Let me know if you want that :)

**Comment by sampan501** [comment]
Sure you can!

**Comment by ghost** [comment]
> Sure you can!

Can provide me with a sample reference on how I should edit the documentation of this particular issue? I highly appreciate that.

**Comment by sampan501** [comment]
To approach I would try two things. First I would try remove the casting to floats, which I believe is done here: https://github.com/neurodata/hyppo/blob/135cfcd6b13a986b09ec7629931bce8676ea5547/hyppo/discrim/_utils.py#L29, and see if the unit tests build. If so, great you are done? If not you need to edit the documentation.

If you are editing the documentation, you will need to edit lines like this: https://github.com/neurodata/hyppo/blob/135cfcd6b13a986b09ec7629931bce8676ea5547/hyppo/discrim/discrim_one_samp.py#L59 to specify the type the inputs in all the methods in `hyppo`. So you would say `ndarray of floats` or something like that

**Comment by ghost** [comment]
> To approach I would try two things. First I would try remove the casting to floats, which I believe is done here:
> 
> https://github.com/neurodata/hyppo/blob/135cfcd6b13a986b09ec7629931bce8676ea5547/hyppo/discrim/_utils.py#L29
> 
> , and see if the unit tests build. If so, great you are done? If not you need to edit the documentation.
> If you are editing the documentation, you will need to edit lines like this:
> 
> https://github.com/neurodata/hyppo/blob/135cfcd6b13a986b09ec7629931bce8676ea5547/hyppo/discrim/discrim_one_samp.py#L59
> 
> to specify the type the inputs in all the methods in `hyppo`. So you would say `ndarray of floats` or something like that

I edited the documentations. Please let me know if everything is alright. 
Just one question: Which unit test should I be running for this? maybe a reference to the file or name of it? Thank you.

**Comment by sampan501** [comment]
There isn't really a specific unit test. However there should be a netlify deploy preview and the site should render the documentation correctly. The log in netlify should be without any errors

**Comment by ghost** [comment]
@sampan501 The netlify link is the same as the one that the bot provided after the initial commit? Should I check that?

**Comment by sampan501** [comment]
Should be the same one, also should be a "deploy-preview" in the checks section

**Comment by bdpedigo** [comment]
Did removing the cast to float not work? I felt that when passing in an array of labels, the labels are often integers or strings but rarely floats, does that make sense?

**Comment by sampan501** [comment]
So changing the text in the documentation is more of a temporary fix. I opened #246 to investigate whether not casting to float changes the test statistic and p-value calculations
