### ISSUE TITLE
address JMLR feedback

### ISSUE THREAD

**Issue by jovo** [neurodata/hyppo#161]
1. Some recent high impact tests are missing. There is for example a whole new set of kernel based tests for two-sample, independence, and goodness of fit tests, that all run in linear time and are very competitive with quadratic time methods. See below
http://papers.nips.cc/paper/6630-a-linear-time-kernel-goodness-of-fit-test
https://dl.acm.org/doi/10.5555/3305381.3305561
http://papers.nips.cc/paper/6147-interpretable-distribution-features-with-maximum-testing-power (https://papers.nips.cc/paper/2016/file/0a09c8844ba8f0936c20bd791130d6b6-Paper.pdf)

2. Related, parameter tuning is missing. In particular kernel-based statistical tests often allow for automatic kernel parameter tuning (and quite sensitive to those). At least heuristics would be helpful here.

3. No goodness of fit tests. This is a major class that would fit into the toolbox quite well.

I'd recommend to rectify at least some these points a bigger impact submission.

**Comment by jovo** [comment]
1. fast tests: add chi-squared and the 1D fast tests
2. flexible kernels: wrapped sklearn kernel stuff
3. goodness of fit tests: sampling based 2-sample test, but read https://www.sciencedirect.com/science/article/pii/S0047259X03002124?via%3Dihub

**Comment by sampan501** [comment]
- [x] separate classes for Energy, MMD, DISCO
- [x] create user guide section
- [x] add independence tutorial
- [x] add k-sample tutorial
- [x] add discriminability tutorial
- [x] add time series tutorial
- [x] add api reference using auto-module
- [x] add flexible kernels using sklearn pairwise kernels and distances
- [x] add fast 1D euclidean tests
- [x] add overview of using a hyppo test
- [x] update readme to sklearn style
- [x] add MANOVA and Hotelling
- [x] add simulations notebooks: independence, ksample
- [x] add simulations notebooks: time series
- [x] move to CircleCI
- [x] make docs more pretty
- [x] add figures from other papers to examples folder
- [x] add change from other branches
- [x] change k-sample sims from 2-sample to k-sample
