### ISSUE TITLE
No module named 'hyppo._utils'

### ISSUE THREAD

**Issue by deadmeat17** [neurodata/hyppo#170]
My issue is about ...

#### Reproducing code example:

```
Sample code to reproduce the problem
```

#### Error message

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  ...
```

#### Version information

- OS: [e.g. macOS]
- Python Version [e.g. 3.7.3]
- Package Version [e.g. 0.0.1]

**Comment by sampan501** [comment]
We just released a new version of the package through pypi! We have conveniently moved a number of our functions into a new module called ``tools``. See here for desired functions: https://hyppo.neurodata.io/api/index.html
