### ISSUE TITLE
rbf and guassian in compute_kern are not the same

### ISSUE THREAD

**Issue by j1c** [neurodata/hyppo#195]
The docstring says
https://github.com/neurodata/hyppo/blob/f7df5bbc5bac49318bd2df651e55d033469dd4e1/hyppo/tools/common.py#L120
but this line doesn't check if the input is `rbf` or `gaussian` 
https://github.com/neurodata/hyppo/blob/f7df5bbc5bac49318bd2df651e55d033469dd4e1/hyppo/tools/common.py#L141

So `rbf` and `gaussian` would be a little different since the `gamma` for `rbf` will be the sklearn default of `1.0 / n_features`. Should that line also check for `rbf`?

**Comment by sampan501** [comment]
Yes good catch. I'll fix that
