### ISSUE TITLE
Add more clear guidelines about how to commit properly

### ISSUE THREAD

**Issue by sampan501** [neurodata/hyppo#218]
My issue is about ...

**Comment by satviktrivedi12** [comment]
Can you please explain the issue properly i want to do this..

**Comment by sampan501** [comment]
Basically, I want to improve the `CONTRIBUTING.md` file to be more clear about best practices on how to name commits, PRs, etc. I would look at the scipy or scikit-learn documentation and link to them in the file.

**Comment by Satarupa22-SD** [comment]
@sampan501 I have created a PR on this please check and let me know if any changes are needed.
