### ISSUE TITLE
Optimize CircleCI pytest modules

### ISSUE THREAD

**Issue by PSSF23** [neurodata/hyppo#221]
#### Is your feature request related to a problem? Please describe.
Currently, `pytest` identifies actual `test` statistic functions as function tests as well, resulting in longer running checks.

#### Describe the solution you'd like
Limit `pytest` to only run on actual tests.

#### Additional context (e.g. screenshots)

**Comment by sampan501** [comment]
> Currently, pytest identifies actual test statistic functions as function tests as well, resulting in longer running checks.

This is `pytest` running the docstring examples
