### ISSUE TITLE
Question about release schedule

### ISSUE THREAD

**Issue by bdpedigo** [neurodata/hyppo#227]
Hi @sampan501 - wondering when you plan on doing a release to PyPI? Reason I ask is that I'd love to have the changes in https://github.com/neurodata/hyppo/pull/212 in a PyPI release so that @kareef928 can fix https://github.com/microsoft/graspologic/issues/775

**Comment by sampan501** [comment]
This week for sure

**Comment by kareef928** [comment]
@sampan501 I'm also wondering when you will do the release to PyPI, I believe this will cause the tests for [microsoft/graspologic#892](https://github.com/microsoft/graspologic/pull/892) to pass

**Comment by sampan501** [comment]
currently drafting the release notes
