### ISSUE TITLE
k-sample HSIC

### ISSUE THREAD

**Issue by rflperry** [neurodata/hyppo#229]
Don't know if it is already included here but dHISC (e.g. k-sample HSIC) test for joint independence of many distributions and is a critical method in causal discovery algorithms. See the paper here: [https://rss.onlinelibrary.wiley.com/doi/full/10.1111/rssb.12235](https://rss.onlinelibrary.wiley.com/doi/full/10.1111/rssb.12235)

**Comment by sampan501** [comment]
yep we have someone working on this: https://github.com/neurodata/hyppo/issues/104
