### ISSUE TITLE
Add more description about types of ndarray in all methods in documentation

### ISSUE THREAD

**Issue by sampan501** [neurodata/hyppo#245]
My issue is about ...

Related to #140

The API reference section of the documentation currently just lists types for `x` and `y` as `ndarray`. It should also mention that the inputs are `ndarray of type float`.

**Comment by ghost** [comment]
@sampan501 I do this. :)

**Comment by ghost** [comment]
@sampan501 As you mentioned above, documentation within the previous file?

**Comment by sampan501** [comment]
Should be in the docstring if each method in `hyppo`. And their base classes

**Comment by ghost** [comment]
@sampan501  Can I get a progress update on this? is it prgressing accordingly?

**Comment by sampan501** [comment]
when you think you are done, you can request a review from me on the PR and I'll look at it
