### ISSUE TITLE
[BUG] scipy 1.8 breaks hyppo import

### ISSUE THREAD

**Issue by bdpedigo** [neurodata/hyppo#303]
#### Reproducing code example:

```
import hyppo.discrim
```

#### Error message
```
/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/hyppo/discrim/__init__.py:1: in <module>
    from .discrim_one_samp import DiscrimOneSample
/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/hyppo/discrim/discrim_one_samp.py:5: in <module>
    from ._utils import _CheckInputs
/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/hyppo/discrim/_utils.py:4: in <module>
    from ..tools import check_ndarray_xy, check_reps, contains_nan, convert_xy_float64
/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/hyppo/tools/__init__.py:1: in <module>
    from .common import *
/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/hyppo/tools/common.py:6: in <module>
    from scipy.stats.stats import _contains_nan
E   ImportError: cannot import name '_contains_nan' from 'scipy.stats.stats' (/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/scipy/stats/stats.py)
```

The function `_contains_nan()` was moved to a different file in scipy 1.8. In general, this is why it's a bad idea to rely on importing private functions.

Recommend just copy-pasting the private function into hyppo explicitly.

**Comment by bdpedigo** [comment]
P.S. @sampan501 would appreciate resolving this as it's breaking tests in graspologic and I'd rather not have to pin our versions for something like this

**Comment by sampan501** [comment]
sure I can make a release for this once it builds

**Comment by bdpedigo** [comment]
thanks @sampan501! LMK if you get a chance to release so we can bump our dependencies to reflect that

**Comment by bdpedigo** [comment]
@sampan501 i know you mentioned you had some other stuff to review prior to releasing - would it be possible to release a patch with just #304 anytime soon? only reason I'm in a rush is that it's breaking everything downstream including people at MSR trying to use graspologic. if not just lmk and we'll just pin our scipy deps for now

**Comment by sampan501** [comment]
I was just going to release it by the end of the week if that works? Or do you need it faster?

**Comment by bdpedigo** [comment]
> I was just going to release it by the end of the week if that works? Or do you need it faster?

oh that works, thanks!
