### ISSUE TITLE
Two typos

### ISSUE THREAD

**Issue by oakla** [neurodata/hyppo#328]
My issue is about ...

#### Snapshot of documentation error:

**Typo 1:**
---
![image](https://user-images.githubusercontent.com/2579439/180630622-feb77460-2c42-4dce-8cf3-62a98b417e8c.png)

**Typo 2:**
---
![image](https://user-images.githubusercontent.com/2579439/180630664-33beaefb-1e30-4de0-a167-8ac41c360d2f.png)

#### Additional context
1. Stray comma: "the, same" 
2. Unfinished sentence: "The method was first introduced by ."

I would just fix these without creating an issue, but the source doesn't seem to be in the repo.

**Comment by sampan501** [comment]
The source for those are in the docstrings of the respective classes
