### ISSUE TITLE
Add Range of Friedman Rafsky Test Statistic

### ISSUE THREAD

**Issue by oakla** [neurodata/hyppo#329]
My issue is about ...
Updating the documentation to include the range of the Friedman Rafsky test statistic

#### Additional context
This is a sub-issue of [issue 121](https://github.com/neurodata/hyppo/issues/121). 

I have been investigating the ranges of some test statistics, and I have made some progress. I would like to contribute the ranges I have determined, starting with Friedman Rafsky.

**Comment by sdroyc** [comment]
Hi! want to your on this issue ! could you help me out how to do it?

**Comment by oakla** [comment]
@sdroyc 
> Hi! want to your on this issue ! could you help me out how to do it?

Issue is resolved. Awaiting review and approval of PR

**Comment by oakla** [comment]
PR #414  submitted: updates documentation to include test statistic range of Friedman Rafsky Test

**Comment by sampan501** [comment]
@oakla PR will automatically close when issue is merged
