### ISSUE TITLE
The statistic returned by the `test` method is different to the statistic returned by the `statistic` method

### ISSUE THREAD

**Issue by oakla** [neurodata/hyppo#330]
My issue is about ...
For independence tests, the `test` method returns a statistic that is different to the statistic returned by the `statistic` method. It seems that the statistic returned by the `test` method has been 'corrected' based on properties of the null distribution. This might be confusing to some people. Maybe it would be nice to mention it in the documentation rather than them having to dig through source code to figure out what is happening?

#### Snapshot of documentation error:

![image](https://user-images.githubusercontent.com/2579439/180641045-1fa8e8ad-1f14-4888-918f-c73512ec78a9.png)

#### Additional context
I'm pretty novice when it comes to these things, so forgive me if this is one of those common practices that everyone but me knows about.

**Comment by sampan501** [comment]
Is this only for Friedman Rafsky, or other tests in hyppo?
