### ISSUE TITLE
Energy statistic is wrong

### ISSUE THREAD

**Issue by vnmabus** [neurodata/hyppo#341]
I was trying to compare the energy statistic implemented in hyppo with the one implemented in my own package, dcor.
However, I found that the statistic in hyppo implements the energy statistic based in Theorem 2 from https://arxiv.org/pdf/1910.08883.pdf, but does it in a wrong way.

In https://github.com/neurodata/hyppo/blob/d0450180d0717a2f73ae55e1f8c1c8413e048a5e/hyppo/ksample/energy.py#L118 the coefficient should be inverted (as one implements the energy from the distance correlation, and not otherwise). Moreover the `x` passed to distance covariance should be the concatenation of `x` and `y`, and the `y` passed should be a label containing zero for samples in `x` and 1 for samples in `y`.

#### Reproducing code example:
```python
from hyppo.ksample import Energy
import dcor
import numpy as np

x = np.arange(100.0)
y = x**2

print("dcor", dcor.energy_distance(x, y))
print("paper formula", dcor.distance_covariance_sqr(np.concatenate([x, y]), np.concatenate([np.zeros(len(x)), np.ones(len(y))])) * 200**4 / (2 * 100**2 * 100**2))
print("hyppo", hyppo.ksample.Energy(bias=True).statistic(x[:, None], y[:, None]))
```

#### Results
```
dcor 3146.5236000000004
paper formula 3146.5235999999986
hyppo 5501.374807500008
```

#### Version information

- OS: Any
- Python Version: Any
- Package Version: 0.3.2

**Comment by sampan501** [comment]
Thank you for this bug report. I will investigate and make changes
