### ISSUE TITLE
Lots missing from API reference

### ISSUE THREAD

**Issue by bdpedigo** [neurodata/hyppo#350]
#### Snapshot of documentation error:

looks like lots of classes are missing, e.g. KSample? unless I am misunderstanding what this page is supposed to be 

<img width="1147" alt="Screen Shot 2023-02-06 at 1 41 26 PM" src="https://user-images.githubusercontent.com/25714207/216986474-e5064369-a053-4f89-a6dd-042c8503095b.png">

**Comment by sampan501** [comment]
fixed
