### ISSUE TITLE
About Module 'hyppo.conditional'

### ISSUE THREAD

**Issue by caimingA** [neurodata/hyppo#359]
My issue is about 
when I want to try the FCIT example code in your [document](documenthttps://hyppo.neurodata.io/user_guide/conditional.html), A **ModuleNotFoundError** came. I am wondering if this is a bug in the current release or just I have done something wrong. 

The detail messages are as follows: 

My code:
```
from hyppo.independence import Hsic
from hyppo.conditional import FCIT
```

Error message:
```
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[3], line 2
      1 from hyppo.independence import Hsic
----> 2 from hyppo.conditional import FCIT

ModuleNotFoundError: No module named 'hyppo.conditional'
```

Version information:

Linux-5.15.0-58-generic-x86_64-with-glibc2.35
Python 3.9.16 (main, Mar  8 2023, 14:00:05) 
[GCC 11.2.0]
hyppo 0.3.2

**Comment by sampan501** [comment]
Hello,

Currently this code has not been released on PyPi yet but will be soon. I would follow the instructions to build from source and run the the command `git checkout dev after cloning`
