### ISSUE TITLE
Incorrect Inference in Overview of Workflow using MGC?

### ISSUE THREAD

**Issue by transpersonify** [neurodata/hyppo#363]
My issue is about the discussion in Overview > Workflow > MGC test: https://hyppo.neurodata.io/get_start/overview.html

#### Snapshot of documentation error:
![image](https://user-images.githubusercontent.com/8897933/236217587-665b9c3c-99a8-45b7-9d25-9ec03bc232f2.png)

Given that MGC measures the correlation between the two variables, the  **null** hypothesis that the two variables are independent.  Given that the p-value < 0.05 then means that we can **_reject_** the null hypothesis of the two variables being independent. And  infer that the two variables are **_related_** (i.e. **_not independent_**).

There is a typo in the explanation or am I missing something?

**Comment by sampan501** [comment]
Yes that's correct. Thank you for the fix!
