### ISSUE TITLE
[Question] Non Euclidean distance metric for discriminability 

### ISSUE THREAD

**Issue by ameliecr** [neurodata/hyppo#418]
Hi hyppo team,

I would like to use a different distance metric instead of the Euclidean distance for the calculation of discriminability. In this case `1-dice_similarity`, so it would also be in [0, 1]. Is this possible?
I know it says in one of the [publications on discriminability](https://doi.org/10.1371/journal.pcbi.1009279) that it can be used with different distance measures but in the hyppo user guide it says that the 'distances must be Euclidean distance'. This is however not mentioned in the reference API so I am not sure if results will be correct when using another distance metric.

Thanks in advance!

**Comment by sampan501** [comment]
If you set the `is_dist` parameter to `False`, and use your inputs as pairwise distance matrices, I believe things should work. See more details here: https://hyppo.neurodata.io/api/generated/hyppo.discrim.discrimonesample#hyppo.discrim.DiscrimOneSample.

**Comment by ameliecr** [comment]
Hi, thank you for the fast response! I am not sure if I am understanding the `is_dist` parameter correctly. Wouldn't I need to set it to `True` if `x` is my pairwise (1-dice) distance matrix?

**Comment by sampan501** [comment]
oh sorry yes that's what I meant

**Comment by sampan501** [comment]
should be the same for the two sample version if you are testing that

**Comment by ameliecr** [comment]
Perfect, that is great to hear. Thanks a lot for your help!
