### ISSUE TITLE
Question: Multidimensional two sample tests with different sample sizes

### ISSUE THREAD

**Issue by diogoseca** [neurodata/hyppo#89]
Hi!

I currently have two multidimensional samples of different sizes. I would like to test whether they were generated by the same distribution. Hyppo has a very good choice of tests for multidimensional samples with equal sizes. However, I've not seen mention on what to do if the sample sizes are unequal.

Do you have any tips on what to do?
Is oversampling a possible solution, or not at all? I've read that having different sample sizes could affect statistical power, so I fear that oversampling might not be the best solution.

Thank you in advance :)

**Comment by sampan501** [comment]
Hi! `hyppo` should work with 2 different multidimensional samples of different sizes, i.e. sample 1 has n samples and p features and sample 2 has m samples and p features.

**Comment by diogoseca** [comment]
Thank you for the clarification @sampan501 !! I misinterpreted "All inputs must have the same number of samples." in the Reference even though what came after was "the shapes must be (n, p) and (m, p) where n and m are the number of samples and p are the number of dimensions".. /facepalm
