### ISSUE TITLE
Recommend exposing TESTS dict or similar

### ISSUE THREAD

**Issue by bdpedigo** [neurodata/hyppo#90]
sklearn exposes a dictionary mapping valid strings for something like a pairwise distance ["euclidean", "l1", etc.] to the corresponding function. Makes it super easy to test if something is a valid key, and get all available options if you are exploring. See [here](https://github.com/scikit-learn/scikit-learn/blob/acbe13c07d204e6ba463f41d2fd39b2a1c776f20/sklearn/metrics/pairwise.py#L912). 

Could be useful to have for hyppo too, basically would expose [this](https://github.com/neurodata/hyppo/blob/da63f814023f956defd0f773b5eb7a59b4f540fa/hyppo/ksample/ksamp.py#L67) as a dictionary called `TESTS`* or something similar. 

*note, IMO might be more confusing to call this `INDEPENDENCE_TESTS` because they can also be used for k-sample, but that's just my opinion

**Comment by sampan501** [comment]
yep! Currently working on this
