### ISSUE TITLE
TypeError at super(Dcorr, self)

### ISSUE THREAD

**Issue by rflperry** [neurodata/hyppo#91]
Error thrown regarding `super(Dcorr, self)` call. Fixed when `super()` instead.

#### Reproducing code example:
```
Dcorr().test(X, Y, workers=-1, reps=1000, auto=False)
```

#### Error message
```
TypeError                                 Traceback (most recent call last)
 in 
----> 1 Dcorr().test(X, Y, workers=-1, reps=1000, auto=False)

~/hyppo/hyppo/independence/dcorr.py in test(self, x, y, reps, workers, auto, bias, c_mat)
    220                 y = self.compute_distance(y, workers=workers)
    221                 self.is_distance = True
--> 222             stat, pvalue = super(Dcorr, self).test(x, y, reps, workers)
    223 
    224         if c_mat:

TypeError: super(type, obj): obj must be an instance or subtype of type
```

#### Version information

synaptomes1
- OS: linux
- Python Version 3.6.9
- Package Version master

**Comment by sampan501** [comment]
Are you using the latest version of ``hyppo``? When I try to reproduce this on ``master``, I'm not getting an error

**Comment by rflperry** [comment]
hmm, ran it again and it works fine now. I think it may have been due to a conflict. Closing.
